version: '3.0'

services:
  proxy:
     image: traefik:1.7
     command:
       - --accesslog=false
       - --loglevel=INFO
       - --entrypoints=Name:api Address::8080
       - --entrypoints=Name:http Address::80
       - --defaultentrypoints=http
       - --api
       - --api.entrypoint=api
       - --api.dashboard=true
       - --docker=true
       - --docker.endpoint=unix:///var/run/docker.sock
       - --docker.watch=true
       - --docker.exposedByDefault=false
     ports:
       - 80:80
     volumes:
       - /var/run/docker.sock:/var/run/docker.sock:ro
     restart: always
     networks:
       - proxy
       - default
     labels:
       traefik.enable: "true"
       traefik.api.frontend.rule: "HostRegexp: traefik.{domain:.+}"
       traefik.api.port: 8080

  prometheus:
    image: prom/prometheus:v2.14.0
    volumes:
      - ./prometheus/:/etc/prometheus/
      - ./volumes/prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus1.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.max-block-duration=2h'
      - '--storage.tsdb.min-block-duration=2h'
      - '--web.enable-lifecycle'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    restart: always
    networks:
      - default
      - proxy
    labels:
      traefik.enable: "true"
      traefik.web.frontend.rule: "HostRegexp: prometheus.{domain:.+}"
      traefik.web.port: 9090
    ports:
      - "9090:9090"

  node-exporter:
    image: prom/node-exporter:v0.18.1
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - ./nodeexporter/textfiles:/textfiles
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
      - --collector.textfile.directory=/textfiles
    restart: always
    networks:
      - default
      - proxy
    labels:
      traefik.enable: "true"
      traefik.web.frontend.rule: "HostRegexp: node-exporter.{domain:.+}"
      traefik.web.port: 9100
    ports:
      - "9100:9100"

  grafana:
    image: grafana/grafana
    user: "104"
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    restart: always
    networks:
      - default
      - proxy
    labels:
      traefik.enable: "true"
      traefik.web.frontend.rule: "HostRegexp: grafana.{domain:.+}"
      traefik.web.port: 3000
    ports:
      - "3000:3000"

networks:
  proxy:
    external: true
